"""add query_logs table

Revision ID: 0138f0ea91b2
Revises: 70c5984c7a18
Create Date: 2026-04-02 17:28:46.051157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0138f0ea91b2'
down_revision: Union[str, None] = '70c5984c7a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_case_id', sa.BigInteger(), nullable=False),
    sa.Column('query_type', sa.String(), nullable=False),
    sa.Column('query_details', sa.Text(), nullable=True),
    sa.Column('documents_requested', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_case_id'], ['claim_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_logs_claim_case_id', 'query_logs', ['claim_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_logs_claim_case_id', table_name='query_logs')
    op.drop_table('query_logs')
    # ### end Alembic commands ###
