"""add claim lifecycle tables

Revision ID: 0d122b7b6ae3
Revises: 7928997c221c
Create Date: 2026-04-01 16:11:37.230252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d122b7b6ae3'
down_revision: Union[str, None] = '7928997c221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_cases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('policy_provider_id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['policy_provider_id'], ['policy_provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_cases_patient_id', 'claim_cases', ['patient_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_case_id', sa.BigInteger(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_case_id'], ['claim_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_case_id')
    )
    op.create_index('ix_claims_claim_case_id', 'claims', ['claim_case_id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_case_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_case_id'], ['claim_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_status_history_claim_case_id', 'status_history', ['claim_case_id'], unique=False)
    op.create_table('pre_auths',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_case_id', sa.BigInteger(), nullable=False),
    sa.Column('form_data_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_case_id'], ['claim_cases.id'], ),
    sa.ForeignKeyConstraint(['form_data_id'], ['form_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_case_id')
    )
    op.create_index('ix_pre_auths_claim_case_id', 'pre_auths', ['claim_case_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_foreign_key(None, 'form_data', 'claim_cases', ['claim_case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_data', type_='foreignkey')
    op.drop_table('settlements')
    op.drop_index('ix_pre_auths_claim_case_id', table_name='pre_auths')
    op.drop_table('pre_auths')
    op.drop_index('ix_status_history_claim_case_id', table_name='status_history')
    op.drop_table('status_history')
    op.drop_index('ix_claims_claim_case_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_claim_cases_patient_id', table_name='claim_cases')
    op.drop_table('claim_cases')
    op.drop_table('patients')
    # ### end Alembic commands ###
