"""add current_stage to claim_cases

Revision ID: 20ab44b7c54e
Revises: 818b63101b1c
Create Date: 2026-04-02 11:08:53.614299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ab44b7c54e'
down_revision: Union[str, None] = '818b63101b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('current_stage', sa.String(), nullable=True))
    op.execute("UPDATE claim_cases SET current_stage = 'PRE_AUTH' WHERE current_stage IS NULL")
    op.alter_column('claim_cases', 'current_stage', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_cases', 'current_stage')
    # ### end Alembic commands ###
