"""add global_variables to hospital_configs

Revision ID: 2fcdb5f118d3
Revises: 808ca8ec57d3
Create Date: 2026-03-20 14:30:19.675905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fcdb5f118d3'
down_revision: Union[str, None] = '808ca8ec57d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_configs', sa.Column('global_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_configs', 'global_variables')
    # ### end Alembic commands ###
