"""replace patient_id with uhid in claim_cases

Revision ID: 48d2a6e535af
Revises: 0d122b7b6ae3
Create Date: 2026-04-01 16:20:26.454926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d2a6e535af'
down_revision: Union[str, None] = '0d122b7b6ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('uhid', sa.String(), nullable=False))
    op.drop_index('ix_claim_cases_patient_id', table_name='claim_cases')
    op.create_index('ix_claim_cases_uhid', 'claim_cases', ['uhid'], unique=False)
    op.drop_constraint('claim_cases_patient_id_fkey', 'claim_cases', type_='foreignkey')
    op.drop_column('claim_cases', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('claim_cases_patient_id_fkey', 'claim_cases', 'patients', ['patient_id'], ['id'])
    op.drop_index('ix_claim_cases_uhid', table_name='claim_cases')
    op.create_index('ix_claim_cases_patient_id', 'claim_cases', ['patient_id'], unique=False)
    op.drop_column('claim_cases', 'uhid')
    # ### end Alembic commands ###
