"""add thread_id to claim_cases

Revision ID: 70c5984c7a18
Revises: c6f62e973ee6
Create Date: 2026-04-02 16:01:16.831191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c5984c7a18'
down_revision: Union[str, None] = 'c6f62e973ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('thread_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'claim_cases', ['thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim_cases', type_='unique')
    op.drop_column('claim_cases', 'thread_id')
    # ### end Alembic commands ###
