"""add policy_provider_id to form_templates

Revision ID: 7928997c221c
Revises: 0f27e95654f5
Create Date: 2026-04-01 15:37:33.866622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7928997c221c'
down_revision: Union[str, None] = '0f27e95654f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first to allow backfill of existing rows
    op.add_column('form_templates', sa.Column('policy_provider_id', sa.UUID(), nullable=True))

    # Backfill existing rows with the only policy provider
    op.execute("UPDATE form_templates SET policy_provider_id = '68d13b05-4971-4cb7-a063-d153ce2025cc' WHERE policy_provider_id IS NULL")

    # Now set not null and add FK
    op.alter_column('form_templates', 'policy_provider_id', nullable=False)
    op.create_foreign_key('fk_form_templates_policy_provider', 'form_templates', 'policy_provider_configs', ['policy_provider_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_templates', type_='foreignkey')
    op.drop_column('form_templates', 'policy_provider_id')
    # ### end Alembic commands ###
