"""add claim_number to claim_cases

Revision ID: 818b63101b1c
Revises: e5f4dca89aa9
Create Date: 2026-04-02 11:05:46.711612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818b63101b1c'
down_revision: Union[str, None] = 'e5f4dca89aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('claim_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_cases', 'claim_number')
    # ### end Alembic commands ###
