"""add claim_status to claim_cases

Revision ID: ab321af780b7
Revises: 20ab44b7c54e
Create Date: 2026-04-02 14:22:25.264018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab321af780b7'
down_revision: Union[str, None] = '20ab44b7c54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('claim_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_cases', 'claim_status')
    # ### end Alembic commands ###
