"""add_claim_case_emails_and_attachments

Revision ID: be62375c984e
Revises: 0138f0ea91b2
Create Date: 2026-04-06 12:27:58.301602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be62375c984e'
down_revision: Union[str, None] = '0138f0ea91b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_case_emails',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_case_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_case_id'], ['claim_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('ix_claim_case_emails_claim_case_id', 'claim_case_emails', ['claim_case_id'], unique=False)
    op.create_index('ix_claim_case_emails_message_id', 'claim_case_emails', ['message_id'], unique=False)
    op.create_table('claim_case_email_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('claim_case_id', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_case_id'], ['claim_cases.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['claim_case_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_case_email_attachments_claim_case_id', 'claim_case_email_attachments', ['claim_case_id'], unique=False)
    op.create_index('ix_claim_case_email_attachments_email_id', 'claim_case_email_attachments', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claim_case_email_attachments_email_id', table_name='claim_case_email_attachments')
    op.drop_index('ix_claim_case_email_attachments_claim_case_id', table_name='claim_case_email_attachments')
    op.drop_table('claim_case_email_attachments')
    op.drop_index('ix_claim_case_emails_message_id', table_name='claim_case_emails')
    op.drop_index('ix_claim_case_emails_claim_case_id', table_name='claim_case_emails')
    op.drop_table('claim_case_emails')
    # ### end Alembic commands ###
