"""add updated_by to status_history

Revision ID: c6f62e973ee6
Revises: ab321af780b7
Create Date: 2026-04-02 15:48:31.319863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f62e973ee6'
down_revision: Union[str, None] = 'ab321af780b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_history', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'status_history', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status_history', type_='foreignkey')
    op.drop_column('status_history', 'updated_by')
    # ### end Alembic commands ###
