"""make claim_case_id optional and remove form_template_id from form_data

Revision ID: e14d1aa9beae
Revises: c6243d847e5b
Create Date: 2026-04-01 22:11:25.832540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14d1aa9beae'
down_revision: Union[str, None] = 'c6243d847e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_data', 'claim_case_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('form_data_form_template_id_fkey', 'form_data', type_='foreignkey')
    op.drop_column('form_data', 'form_template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('form_template_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('form_data_form_template_id_fkey', 'form_data', 'form_templates', ['form_template_id'], ['id'])
    op.alter_column('form_data', 'claim_case_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
