"""remove current_stage from claim_cases

Revision ID: e5f4dca89aa9
Revises: e14d1aa9beae
Create Date: 2026-04-01 22:16:27.824666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f4dca89aa9'
down_revision: Union[str, None] = 'e14d1aa9beae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_cases', 'current_stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('current_stage', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
