"""add email validation fields to claim_case_emails

Revision ID: e91243b4df9a
Revises: 790db59546db
Create Date: 2026-04-09 12:49:59.243577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91243b4df9a'
down_revision: Union[str, None] = '790db59546db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_claim_case_documents_claim_case_id', 'claim_case_documents', ['claim_case_id'], unique=False)
    op.add_column('claim_case_emails', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('claim_case_emails', sa.Column('ai_suggested_status', sa.String(), nullable=True))
    op.add_column('claim_case_emails', sa.Column('ai_suggested_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('claim_case_emails', sa.Column('ai_suggested_claim_number', sa.String(), nullable=True))
    op.add_column('claim_case_emails', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('claim_case_emails', sa.Column('ai_query_details', sa.Text(), nullable=True))
    op.add_column('claim_case_emails', sa.Column('ai_documents_requested', sa.Text(), nullable=True))
    op.add_column('claim_case_emails', sa.Column('validation_status', sa.String(), server_default='PENDING', nullable=False))
    op.add_column('claim_case_emails', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('claim_case_emails', sa.Column('validated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'claim_case_emails', 'users', ['validated_by'], ['id'])
    op.create_index('ix_claims_claim_case_id', 'claims', ['claim_case_id'], unique=False)
    op.create_unique_constraint(None, 'claims', ['claim_case_id'])
    op.alter_column('form_data', 'claim_case_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_pre_auths_claim_case_id', 'pre_auths', ['claim_case_id'], unique=False)
    op.create_unique_constraint(None, 'pre_auths', ['claim_case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_auths', type_='unique')
    op.drop_index('ix_pre_auths_claim_case_id', table_name='pre_auths')
    op.alter_column('form_data', 'claim_case_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'claims', type_='unique')
    op.drop_index('ix_claims_claim_case_id', table_name='claims')
    op.drop_constraint(None, 'claim_case_emails', type_='foreignkey')
    op.drop_column('claim_case_emails', 'validated_by')
    op.drop_column('claim_case_emails', 'validated_at')
    op.drop_column('claim_case_emails', 'validation_status')
    op.drop_column('claim_case_emails', 'ai_documents_requested')
    op.drop_column('claim_case_emails', 'ai_query_details')
    op.drop_column('claim_case_emails', 'ai_summary')
    op.drop_column('claim_case_emails', 'ai_suggested_claim_number')
    op.drop_column('claim_case_emails', 'ai_suggested_amount')
    op.drop_column('claim_case_emails', 'ai_suggested_status')
    op.drop_column('claim_case_emails', 'is_read')
    op.drop_index('ix_claim_case_documents_claim_case_id', table_name='claim_case_documents')
    # ### end Alembic commands ###
