"""remove policy_number from claim_cases

Revision ID: fe67e403dd8c
Revises: 48d2a6e535af
Create Date: 2026-04-01 16:27:53.033455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe67e403dd8c'
down_revision: Union[str, None] = '48d2a6e535af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_cases', 'policy_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_cases', sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
